; LilyGo T-LoRa Pager — MeshReliable variant
[env:tlora-pager-lr1121]
custom_meshtastic_hw_model = 103
custom_meshtastic_hw_model_slug = T_LORA_PAGER
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = LILYGO T-LoRa Pager (MeshReliable)
custom_meshtastic_tags = LilyGo
custom_meshtastic_requires_dfu = true
custom_meshtastic_partition_scheme = 16MB

extends = esp32s3_base
board = t-deck-pro
board_check = true
board_build.partitions = default_16MB.csv
upload_protocol = esptool

build_src_filter =
  ${esp32s3_base.build_src_filter}
  +<../variants/esp32s3/tlora-pager>

build_flags =
  ${esp32s3_base.build_flags}
  -I variants/esp32s3/tlora_pager_lr1121
  -D T_LORA_PAGER
  -D BOARD_HAS_PSRAM
  -D HAS_SDCARD
  -D ENABLE_ROTARY_PULLUP
  -D ENABLE_BUTTON_PULLUP
  -D ROTARY_BUXTRONICS
  -D HAS_VOICE_MEMO
  -D VOICE_MEMO_ES8311

lib_deps =
  ${esp32s3_base.lib_deps}
  lovyan03/LovyanGFX@1.2.21
  https://github.com/meshtastic/ESP8266Audio/archive/343024632ee78d6216907b2353fc943a62422d80.zip
  earlephilhower/ESP8266SAM@1.1.0
  adafruit/Adafruit DRV2605 Library@1.2.4
  lewisxhe/PCF8563_Library@1.0.1
  lewisxhe/SensorLib@0.3.4
  https://github.com/pschatzmann/arduino-audio-driver/archive/v0.2.1.zip
  https://github.com/mverch67/BQ27220/archive/07d92be846abd8a0258a50c23198dac0858b22ed.zip
  https://github.com/mverch67/RotaryEncoder/archive/da958a21389cbcd485989705df602a33e092dd88.zip
